name: ci
on:
  push:
    branches:
      - master
      - main

  repository_dispatch:
    types: [update_zettelkasten]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-roamlinks-plugin
      - run: mkdocs gh-deploy --force
